version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: vestige-postgres
    environment:
      POSTGRES_DB: vestige
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: