spring:
  application:
    name: Vestige_BE

  # Enable scheduling for escrow transfers
  task:
    scheduling:
      enabled: true
      pool:
        size: 2

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: Asia/Ho_Chi_Minh

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  currency: vnd
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:900000}  # 15 minutes for access token
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days for refresh token

# App Configuration
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  cookie:
    secure: ${COOKIE_SECURE:false}  # Set to true in production with HTTPS
    same-site: ${COOKIE_SAME_SITE:STRICT}
    domain: ${COOKIE_DOMAIN:}  # Set your domain in production

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,PATCH,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: true
  max-age: 3600

server:
  port: ${PORT:8080}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**

# Logging
logging:
  level:
    se.vestige_be: INFO
    org.springframework.web.socket: DEBUG
    com.stripe: DEBUG

---
# Local Profile
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/vestige
    username: postgres
    password: ${DATABASE_PASSWORD:12345}
  jpa:
    show-sql: true

# Use environment variables for Stripe keys in local development
stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}
  currency: vnd

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false

logging:
  level:
    se.vestige_be: WARN
    root: WARN